services:
  web:
    environment:
      - PYTHONUNBUFFERED=1
      - AGNET_SECTION_KEY=${AGNET_SECTION_KEY}
    build: .
    command: python app.py
    volumes:
      - .:/app  # Maps current directory to /app inside container
    ports:
      - "8000:8000"