name: Deploy Service

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            mkdir -p /apps/${{ github.event.repository.name }}
            cd /apps/${{ github.event.repository.name }}
            if [ -d ".git" ]; then
              git pull
            else
              git clone git@github.com:F2F-Enterprise-Project/${{ github.event.repository.name }}.git .
            fi
            docker build -t ${{ github.event.repository.name }} .
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            docker run -d -p 3005:3005 --name ${{ github.event.repository.name }} ${{ github.event.repository.name }}
